### ISSUE TITLE
IllIllI - Primary price is used for market orders, rather than secondary prices, as the comments indicate should be used

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#169]
IllIllI

medium

# Primary price is used for market orders, rather than secondary prices, as the comments indicate should be used

## Summary

Market orders use the primary (oldest) price for market orders, rather than the secondary (fresher) price, even though the comments say the opposite should be done

## Vulnerability Detail

The comments for the function state:
```solidity
    // for market orders, set the min and max values of the customPrice for the indexToken
    // to either secondaryPrice.min or secondaryPrice.max depending on whether the order
    // is an increase or decrease and whether it is for a long or short
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/order/BaseOrderUtils.sol#L184-L186

but the code uses the `primaryPrice`

## Impact

Users will get the wrong execution prices if there are price gaps, leading to false losses for the other side of the trade.

## Code Snippet

Uses the primary price, not the secondary price:
```solidity
// File: gmx-synthetics/contracts/order/BaseOrderUtils.sol : BaseOrderUtils.setExactOrderPrice()   #1

218            //     - short: use the smaller price
219            // decrease order:
220            //     - long: use the smaller price
221            //     - short: use the larger price
222            bool shouldUseMaxPrice = isIncrease ? isLong : !isLong;
223    
224            if (orderType == Order.OrderType.MarketIncrease ||
225                orderType == Order.OrderType.MarketDecrease ||
226                orderType == Order.OrderType.Liquidation) {
227    
228 @>             Price.Props memory price = oracle.getPrimaryPrice(indexToken);
229    
230                oracle.setCustomPrice(indexToken, Price.Props(
231                    price.pickPrice(shouldUseMaxPrice),
232                    price.pickPrice(shouldUseMaxPrice)
233                ));
234    
235                return;
236            }
237    
238:           if (orderType == Order.OrderType.LimitIncrease ||
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/order/BaseOrderUtils.sol#L218-L238

Consider a case where the user submits a market order with an acceptable price of 100, then the (primary,secondary) price comes in at (19,20) for the first block of the order then (20,9999) for the next. In this case the order will be executed during the second block, but the user will have gotten a price of 20, rather than the acceptable price of 100, so they can exit immediately for a profit.

## Tool used

Manual Review

## Recommendation

Use the secondary price so that they get the newer price or the acceptable price, whichever is smaller

**Comment by xvi10** [comment]
the comment is incorrect, primary price should be used for market orders, an example of this is described in https://github.com/sherlock-audit/2023-02-gmx-judging/issues/181#issuecomment-1488053852

**Comment by IllIllI000** [comment]
@xvi10 the example I give above is of a single signer signing blocks in the way you described in #185 – can you elaborate on what specifically is wrong with the example?

**Comment by xvi10** [comment]
in the example:

1. time is 100, price is 2000, latest block is 300
2. Oracle keepers will sign: timestamp: 100, price: 2000, block range: 300-300
3. User creates an order in block 302
4. time is 101, price is 2010, latest block is 305
5. Oracle keepers will sign: timestamp: 101, price: 2010, block range: 301-305
6. The order will be executed with price 2010
7. It should not be possible to execute the order with price 2000, since the block range for that report is 300-300, and the order block 302 is not within the range 300-300

in this case, when executing the order, the order keeper only needs to pass in the 2010 price, which would be the primary price

the order keeper can pass in prices that are reported later, e.g. price 2020 block range: 306-310, which would be recorded as a secondary price

but in https://github.com/gmx-io/gmx-synthetics/blob/main/contracts/order/IncreaseOrderUtils.sol#L97 we validate that the order updatedAtBlock must be within of all oracle block ranges, so passing in a price with block range: 306-310 when the order updatedAtBlock is 302 would result in the transaction reverting

**Comment by xvi10** [comment]
i'm not sure i understand the question, if price is 5000 instead, the example should be:

1. time is 100, price is 2000, latest block is 300
2. Oracle keepers will sign: timestamp: 100, price: 2000, block range: 300-300
3. User creates an order in block 302
4. time is 101, price is 5000, latest block is 305
5. Oracle keepers will sign: timestamp: 101, price: 5000, block range: 301-305
6. The order will be executed with price 5000
7. It should not be possible to execute the order with price 2000, since the block range for that report is 300-300, and the order block 302 is not within the range 300-300

**Comment by IllIllI000** [comment]
@xvi10 For step 7, why is it not possible? The code is checking that the provided blocks fall on [either side of the order](https://github.com/sherlock-audit/2023-02-gmx-IllIllI000/blob/967872f61f65d9d48182052f9bac379341ac544a/gmx-synthetics/contracts/order/IncreaseOrderUtils.sol#L96-L101) but I don't see where the price is forced to be within a particular signer's block range. What prevents the keeper from providing, e.g. blocks 300-300 from one signer, and in addition, block 301-305 from another?

**Comment by xvi10** [comment]
300-300 should fail because of https://github.com/gmx-io/gmx-synthetics/blob/main/contracts/oracle/OracleUtils.sol#L129?

**Comment by IllIllI000** [comment]
@hrishibhat agree with sponsor – invalid
