### ISSUE TITLE
IllIllI - Order keepers can use oracle prices from far in the past

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#185]
IllIllI

medium

# Order keepers can use oracle prices from far in the past

## Summary

The readme states that `Order keepers and frozen order keepers could potentially extract value through transaction ordering, delayed transaction execution etc, this will be partially mitigated with a keeper network`. That mitigation solves delayed order, but does not prevent immediate execution using old prices.

## Vulnerability Detail

Market orders allow prices in the past, and a keeper may use a price further in the past than is necessary, in order to gain some advantage (e.g. a kickback). There is a [limit](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/Oracle.sol#L438) but in a fast-moving market, prices can change a lot.

## Impact

A better price for one user means a worse price for the other side of the trade, and larger losses.

## Code Snippet

Market orders are allowed to use prices from before the order was submitted:
```solidity
// File: gmx-synthetics/contracts/order/IncreaseOrderUtils.sol : IncreaseOrderUtils.validateOracleBlockNumbers()   #1

89         function validateOracleBlockNumbers(
90             uint256[] memory minOracleBlockNumbers,
91             uint256[] memory maxOracleBlockNumbers,
92             Order.OrderType orderType,
93             uint256 orderUpdatedAtBlock,
94             uint256 positionIncreasedAtBlock
95         ) internal view {
96             if (orderType == Order.OrderType.MarketIncrease) {
97  @>             OracleUtils.validateBlockNumberWithinRange(
98                     minOracleBlockNumbers,
99                     maxOracleBlockNumbers,
100                    orderUpdatedAtBlock
101                );
102                return;
103:           }
```
https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/order/IncreaseOrderUtils.sol#L89-L103

## Tool used

Manual Review

## Recommendation

Require the keeper to provide a signature from the oracle archive node stating that there is no price available closer to the given block

**Comment by xvi10** [comment]
> Market orders are allowed to use prices from before the order was submitted

Oracle keepers will sign a price with a block range based on the last signed block and latest observed block

For example:

1. time is 100, price is 2000, latest block is 300
2. Oracle keepers will sign: timestamp: 100, price: 2000, block range: 300-300
3. User creates an order in block 302
4. time is 101, price is 2010, latest block is 305
5. Oracle keepers will sign: timestamp: 101, price: 2010, block range: 300-305
6. The order will be executed with price 2010
7. It should not be possible to execute the order with price 2000, since the block range for that report is 300-300, and the order block 302 is not within the range 300-300

**Comment by IllIllI000** [comment]
@xvi10 For a specific signature that holds, but if there are 10 signatures, and the minimum number of signers is five, can’t the keeper choose the worst 5 (e.g. ones that had a downtime and have a wide block range due to it)?

**Comment by IllIllI000** [comment]
@xvi10 since `it is possible to execute orders with the signatures for the 5 oracle keepers that were down but are now back up` it’s possible for a malicious keeper to take advantage if they’re looking for this scenario and are the first ones to execute the order, so even though it’s unlikely, there’s still the risk and shouldn’t this be confirmed no-fix?

**Comment by xvi10** [comment]
the issue reported is that "Order keepers can use oracle prices from far in the past"

as mentioned, when the 5 oracle keepers are back up, they would sign the block range either based on the latest block observed, so even if using those results orders would still be executed with latest prices instead of old prices

so the issue doesn't seem valid to me

**Comment by IllIllI000** [comment]
@hrishibhat agree with sponsor – invalid
