### ISSUE TITLE
hack3r-0m - same signature can be used multiple times for validation in oracle while setting prices

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-gmx-judging#208]
hack3r-0m

high

# same signature can be used multiple times for validation in oracle while setting prices

## Summary

same signature can be used multiple times for validation in oracle while setting prices

## Vulnerability Detail

when keepers submit prices, they submit signature which to preserve integrity and establishing prices are actually transmitted by keeper. while setting prices in oracle, each signature and data is recovered to signer and check against expected signer.

keeper can steal other keeper's  data + signature from previously executed round and use it in next round and it will be accepted. the only uniqueness in data is `blockhash` which can be 0 if difference is more than 256 blocks.

## Impact

keeper can collect various such signatures with zero blockhash which can result is skewed min / max / median and mean prices and trades would be settle against that.

## Code Snippet

- https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/Oracle.sol#L518
- https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/OracleUtils.sol#L249
- https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/Oracle.sol#L464-L465

## Tool used

Manual Review

## Recommendation

use `block.number` as uniqueness or mark signature as used (for e.g mapping from bytes32 to bool) and check against it

**Comment by hack3r-0m** [comment]
Escalate for 10 USDC
dup of https://github.com/sherlock-audit/2023-02-gmx-judging/issues/74

**Comment by hack3r-0m** [comment]
It should be high severity under https://docs.sherlock.xyz/audits/judging/judging#how-to-identify-a-high-issue
> Definite loss of funds without limiting external conditions.

**Comment by IllIllI000** [comment]
This issue talks about keepers being able to re-use signatures fetched by other keepers from the oracle archive. There is no advantage conferred by doing this, since the oracle archive will just return the same data as the keeper 'took' from other keepers. The block hash does not include any useful information, and the signature includes the [block rage](https://github.com/sherlock-audit/2023-02-gmx/blob/main/gmx-synthetics/contracts/oracle/OracleUtils.sol#L258-L259) which ensures that the signature is only valid for the orders occuring during that time period. This issue is _not_ the same as #74, which talks about using a valid signature for the specific block range, multiple times in the same transaction, for a single order. - Invalid

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid issue
As pointed out by the Lead Watson's comment, the issue is not valid as there is a check for the block range.
